
import java.util.Objects;

/**
 * Class for a Token generated by the Lexer
 */
public class Token {

    private TokenType type;
    private String stringValue = null;
    private long numberValue = 0;
    private char charValue = 0;

    private int row;
    private int column;

    public static final Token EOF_TOKEN = new Token();

    private Token(int row, int column){
        this.row = row;
        this.column = column;
    }

    /**
     * Constructor de un token de tipo NUMERAL. Arroja excepción si se especifica un tipo de token incorrecto
     */
    public Token(TokenType type, long numberValue, int row, int column) throws InvalidTokenTypeException {
        this(row, column);
        if (type != TokenType.NUMERAL){
            throw new InvalidTokenTypeException();
        }
        this.type = type;
        this.numberValue = numberValue;
    }

    /**
     * Construye una palabra reservada o un símbolo. Arroja excepción si se especifica un tipo de token incorrecto
     */
    public Token(TokenType type, char charValue, int row, int column) throws InvalidTokenTypeException {
        this(row, column);
        if (type != TokenType.KEYWORD && type != TokenType.SYMBOL) {
            throw new InvalidTokenTypeException();
        }
        this.type = type;
        this.charValue = charValue;
    }

    /**
     *Construye un ID o un string. Arroja excepción si se especifica un tipo de token incorrecto
     */
    public Token(TokenType type, String stringValue, int row, int column) throws InvalidTokenTypeException {
        this(row, column);
        if (type != TokenType.IDENTIFIER && type!= TokenType.STRING)
            throw new InvalidTokenTypeException();

        this.type = type;
        this.stringValue = stringValue;
    }

    private Token(){
        type = TokenType.EOF;
    }

    public TokenType getType() {
        return type;
    }

    
    public String getStringValue() {
        return stringValue;
    }

  
    public long getNumberValue() {
        return numberValue;
    }

   
    public char getCharValue() {
        return charValue;
    }

    int getRow() {
        return row;
    }

    int getColumn() {
        return column;
    }

    @Override
    public String toString() {
        String value;
        switch (type){
            case KEYWORD:
                value = SpecialCharacter.characterStringMap.get(charValue);
                break;
            case SYMBOL:
                value = "" + getCharValue();
                break;
            case IDENTIFIER:
            case STRING:
                value = getStringValue();
                break;
            case NUMERAL:
                value = "" + getNumberValue();
                break;
            case EOF:
                return "EOF";
            default:
                value = "undefined";
        }
        return type.toString() + " " + value + " at " + row + ":" + column;
    }

    /**
     *Compara dos tokens. Dos tokens son iguales si tienen el mismo tipo, valor y posición
     */
    @Override
    public boolean equals(Object other){
        if(! (other instanceof Token))
            return false;
        Token otherToken = (Token) other;

        return type == otherToken.type
                && (Objects.equals(stringValue, otherToken.stringValue))
                && charValue == otherToken.charValue
                && numberValue == ((Token) other).numberValue
                && row == otherToken.row
                && column == otherToken.column ;
    }
}
